# Generated by Django 5.0.6 on 2024-07-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Тип Еды',
            },
        ),
    ]
