# Generated by Django 5.0.6 on 2024-07-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_button'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='button',
            options={'verbose_name': 'Кнопка', 'verbose_name_plural': 'Кнопка'},
        ),
    ]
