# Generated by Django 5.0.6 on 2024-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=55, verbose_name='Номер телефона')),
                ('persone', models.CharField(choices=[('1 ', '1 - Persone'), ('2 ', '2 - Persone'), ('3 ', '3 - Persone'), ('4 ', '4 - Persone'), ('5 ', '5 - Persone')], max_length=20, verbose_name='Количество людей')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.CharField(choices=[('10:00 AM', '10:00 AM'), ('11:00 AM', '11:00 AM'), ('12:00 AM', '12:00 AM'), ('1:00 AM', '1:00 AM'), ('2:00 AM', '2:00 AM'), ('3:00 AM', '3:00 AM')], max_length=20, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Резервация',
                'verbose_name_plural': 'Резервации',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=100, verbose_name='ID пользователя telegram')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('chat_id', models.CharField(max_length=100, verbose_name='Чат ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь телеграм',
                'verbose_name_plural': 'Пользователи телеграма',
            },
        ),
    ]
